#' Summarize the GSEA results by heatmap
#'
#' Plot a heatmap based on a list with different GSEA category annotation.
#'
#' @param dta the input GSEA result lists.
#' @param cate GSEA annotation category, like h, or kegg.
#' @param NES_thresh filter the non-sig results, if NULL then no filtering.
#' @param only_sig whether only plotting significant gene sets (FDR <= .25).
#' @param return_comb whether return the Combined results.
#' @param row_font_size fontsize for row labels.
#' @param col_font_size fontsize for column labels.
#' @param col_order_new new order of samples in matrix, only works if cluster_columns is FALSE.
#' @param width width of the heatmap.
#' @param height height of the heatmap.
#' @param output_name the name of output file.
#' @param color_palette color used in heatmap.
#' @param ... additional parameters to Heatmap.
#'
#' @return A data.table if return_comb is TRUE.
#'
#' @export
GSEA_heatmap <- function(dta,
    cate          = "h",
    NES_thresh    = NULL,
    only_sig      = FALSE,
    return_comb   = TRUE,
    row_font_size = 5,
    col_font_size = 8,
    col_order_new = NULL,
    width         = 4,
    height        = 6,
    output_name   = "hallmark",
    color_palette = c("navy", "white", "firebrick3"),
    ...) {
  if (!("ComplexHeatmap" %in% utils::installed.packages()[, "Package"])) stop("(EE) Require the package ComplexHeatmap.")

  pathway <- pval <- NES <- N <- sample_id <- is_sig <- padj <- NULL

  comb_cate <- lapply(names(dta), \(x) {
                        dta[[x]][[cate]] %>%
                          .[, sample_id := x] %>%
                          .[, is_sig := 0] %>%
                          .[padj <= .25, is_sig := 1] %>%
                          .[, .(pathway, pval, padj, NES, sample_id, is_sig)]
    }) %>%
    rbindlist

  #- Remove category not presented in all data.
  comb_cate <- comb_cate[, .N, by = "pathway"][N != length(dta)]$pathway %>%
    {comb_cate[! (pathway %in% .)]}

  dta_1 <- dcast(comb_cate, pathway ~ sample_id, value.var = "NES")
  mtx_1 <- dta_1[, - "pathway"] %>%
    as.matrix %>%
    set_rownames(dta_1$pathway)

  #- 1, sig; 0, non-sig.
  dta_2 <- dcast(comb_cate, pathway ~ sample_id, value.var = "is_sig")
  mtx_2 <- dta_2[, - "pathway"] %>%
    as.matrix %>%
    set_rownames(dta_2$pathway)

  if (! is.null(col_order_new)) {
    mtx_1 <- mtx_1[, col_order_new]
    mtx_2 <- mtx_2[, col_order_new]
  }

  #- Filtering only apply to non-sig entries.
  if (!is.null(NES_thresh)) {
    # browser()
    mtx_3 <- mtx_1
    mtx_3[] <- 0
    mtx_3[(abs(mtx_1) >= NES_thresh)] <- 1

    #- !! Keep sig entries.
    mtx_3 <- mtx_3 + mtx_2

    cc_1 <- (rowSums(mtx_3) >= 1)

    mtx_1 <- mtx_1[cc_1, ]
    mtx_2 <- mtx_2[cc_1, ]
  }

  if (only_sig) {
    cc_1 <- (rowSums(mtx_2) >= 1)
    mtx_1 <- mtx_1[cc_1, ]
    mtx_2 <- mtx_2[cc_1, ]
  }

  if (nrow(mtx_1) > 0) {
    pdf(paste0("GSEA_", output_name, ".pdf"), width = width, height = height)
    ht_color <- circlize::colorRamp2(c(-2.5, 0, 2.5), color_palette)
    ht_1 <- ComplexHeatmap::Heatmap(mtx_1,
                                    name            = "NES",
                                    col             = ht_color,
                                    row_names_gp    = grid::gpar(fontsize = row_font_size),
                                    column_names_gp = grid::gpar(fontsize = col_font_size),
                                    cell_fun     = function(j, i, x, y, w, h, fill) {
                                      if (mtx_2[i, j] == 1) {
                                        grid::grid.text("\u00B7", x, y)
                                      }
                                    }, ...)
                                    # heatmap_legend_param = list(title = ""), ...)
    ComplexHeatmap::draw(ht_1)
    dev.off()
  } else {
    message("(II) Empty matrix for heatmap!")
  }

  if (return_comb) return(comb_cate)
}


#' Flat and save GSEA annotation generated by fgsea.
#'
#' Taken a list with different GSEA category annotation, save the results and plots.
#'
#' @param x the input list, with names like c("input_gene", "h", "c2").
#' @param db GSEA annotation database, MUST be in the same order of elements in x.
#' @param prefix_name names used for plot folders, normal the comparisons.
#' @param proj_name data projects.
#' @param output_dir dir to save outputs and plots.
#' @param keep_all keep all gene sets for sepecified groups.
#' @param width width of figures.
#' @param height height of figures
#' @param save_png boolean, TRUE to save figures to png files, FALSE to save in pdf files.
#'
#' @return A vector of colors
#'
#' @export
flat_GSEA <- function(x,
    db,
    prefix_name,
    proj_name,
    output_dir = "./gsea_plot",
    keep_all = c("h", "kegg"),
    width = 7,
    height = 5,
    save_png = TRUE) {
  if (!("fgsea" %in% utils::installed.packages()[, "Package"])) stop("(EE) Require the package fgsea")

  i <- padj <- one_db <- NULL

  #- better with foreach, I dont like mapply.
  #- i is the db list  name (e.g., h, kegg), the order MUST match names in db
  foreach(i = names(x)[-1], one_db = db) %do% {
    out_name <- paste0(proj_name, "_", prefix_name)
    #- One comparison.
    proj_dir <- file.path(output_dir, out_name)
    if (!dir.exists(proj_dir)) dir.create(proj_dir, showWarnings = FALSE, recursive = TRUE)
    fwrite(x[[i]], file.path(proj_dir, paste0(i, ".csv")), sep = "\t")

    #- Default FDR used by GSEA.
    if (! i %in% keep_all) {
      s_dt <- x[[i]][padj <= .25] %>% na.omit
    } else {
      s_dt <- na.omit(x[[i]])
    }

    if (nrow(s_dt) > 0) {
      #- Plot foldes for h, kegg, etc.
      proj_plt_dir <- file.path(proj_dir, i)
      if (!dir.exists(proj_plt_dir)) dir.create(proj_plt_dir, showWarnings = FALSE, recursive = TRUE)
      fn_GSEA_enrich_plot(s_dt, one_db, x$input_gene, output_dir = proj_plt_dir, out_name = out_name, width = width, height = height, save_png = save_png)
    }
  }
}

#- Helper functioin. dta, fgsea results, db, msigdbr;
fn_GSEA_enrich_plot <- function(dta, db, gene, output_dir = ".", out_name, width, height, save_png) {
  pathway <- NULL

  lapply(dta$pathway, \(x) {
           fn_GSEA_single_enrich_plot(dta        = dta,
                                      db         = db,
                                      gene       = gene,
                                      gset       = x,
                                      output_dir = output_dir,
                                      out_name   = out_name,
                                      width      = width,
                                      height     = height,
                                      save_png   = save_png)
    }
  )
}

#- dta, fgsea output, a data.table
#- db, gene sets contains gset
#- gene, the "inputgene", with symbol and fold changes.
#- gset, pathway to plot.
fn_GSEA_single_enrich_plot <- function(dta, db, gene, gset, output_dir = ".", out_name, width, height, save_png) {
  pathway <- NULL
  p01 <- fgsea::plotEnrichment(db[[gset]], gene) +
    labs(title = gset) +
    # annotate("text", Inf, Inf, label = paste0("NES: ", round(dta[pathway == gset]$NES, 2), "\n", "FDR: ", round(dta[pathway == gset]$padj, 2)), hjust = 1, vjust = 1)
    annotate("text", Inf, Inf, label = paste0("NES: ", round(dta[pathway == gset]$NES, 2), "\n", "FDR: ", signif(dta[pathway == gset]$padj, 2)), hjust = 1, vjust = 1)

    if (save_png) {
      ggsave(file.path(output_dir, paste0(out_name, "_", sub("/", "_", gset, fixed = TRUE), ".png")), p01, width = width, height = height)
    } else {
      ggsave(file.path(output_dir, paste0(out_name, "_", sub("/", "_", gset, fixed = TRUE), ".pdf")), p01, width = width, height = height)
  }
}
